/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_itshighnoon_nowplaying_NowPlaying */

#ifndef _Included_us_itshighnoon_nowplaying_NowPlaying
#define _Included_us_itshighnoon_nowplaying_NowPlaying
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_itshighnoon_nowplaying_NowPlaying
 * Method:    get
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_us_itshighnoon_nowplaying_NowPlaying_get
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
